import type { KnowledgeCategory, KnowledgeEntry } from "./types";

export const CATEGORY_LABELS: Record<KnowledgeCategory, string> = {
  returns: "收益与净值",
  risk: "风险指标",
  factors: "因子与排名",
  portfolio: "组合与风控",
  validation: "回测与统计验证",
  "fund-basics": "基金基础",
  "stock-basics": "股票基础",
  data: "数据口径",
};

const ref = (file: string, line: number, label: string) => ({ file, line, label });
const commonCautions = ["任何单一指标都不应单独作为投资决策依据。", "历史统计不保证未来继续有效。"];

export const KNOWLEDGE_ENTRIES: KnowledgeEntry[] = [
  {
    slug: "total-return", title: "累计收益", aliases: ["总收益", "Total Return"], category: "returns",
    summary: "从区间起点到终点的总收益率。",
    definition: ["累计收益反映整个区间净值增长，不做年化。", "基金研究优先使用含分红的连续总收益序列。"],
    formula: "期末净值 ÷ 期初净值 − 1",
    systemConvention: ["本系统收益率以小数存储，页面按百分比展示。", "V2 净值曲线起点为 1，累计收益等于期末策略净值−1。"],
    direction: "higher", directionLabel: "通常越高越好",
    cautions: ["必须同时比较回撤、波动、费用和基准。", ...commonCautions],
    related: ["annualized-return", "excess-return", "b0-benchmark"],
    codeRefs: [ref("apps/api/app/services/quant_v2.py", 272, "V2收益汇总")],
  },
  {
    slug: "annualized-return", title: "年化收益率", aliases: ["年化收益", "Annualized Return", "CAGR"], category: "returns",
    summary: "把区间收益按 252 个交易日折算成一年的复合收益。",
    definition: ["用于比较不同长度区间的收益，但短区间年化会放大偶然波动。"],
    formula: "(1 + 区间总收益)^(252 ÷ 交易日数) − 1",
    systemConvention: ["本系统统一按每年 252 个交易日折算。"],
    direction: "higher", directionLabel: "通常越高越好",
    cautions: ["样本很短时不宜把年化结果外推。", ...commonCautions],
    related: ["total-return", "annual-volatility", "calmar-ratio"],
    codeRefs: [ref("apps/api/app/services/quant_stats.py", 100, "年化函数")],
  },
  {
    slug: "excess-return", title: "超额收益", aliases: ["主动收益", "Excess Return"], category: "returns",
    summary: "策略收益减去基准收益。",
    definition: ["用于回答策略是否比简单基准多赚，而不是只看绝对收益。"],
    formula: "策略累计收益 − 基准累计收益",
    systemConvention: ["基金 V2 与验证默认对比候选池 B0 等权基准。"],
    direction: "higher", directionLabel: "越高越好",
    cautions: ["策略和基准必须使用同一日期、同一费用和可投资范围。", ...commonCautions],
    related: ["b0-benchmark", "information-ratio", "white-reality-check"],
    codeRefs: [ref("apps/api/app/services/quant_validation.py", 400, "验证超额收益")],
  },
  {
    slug: "win-rate", title: "胜率", aliases: ["日胜率", "Win Rate"], category: "returns",
    summary: "收益为正的交易日占比。",
    definition: ["胜率只描述正负次数，不反映每次赚多少或亏多少。"],
    systemConvention: ["本系统日胜率 = 正日收益天数 ÷ 有效日收益天数。"],
    direction: "contextual", directionLabel: "高不一定更好",
    cautions: ["低胜率的大盈小亏策略可能优于高胜率的小盈大亏策略。", ...commonCautions],
    related: ["total-return", "max-drawdown"],
    codeRefs: [ref("apps/api/app/services/quant_validation.py", 296, "风险收益汇总")],
  },
  {
    slug: "annual-volatility", title: "年化波动率", aliases: ["波动率", "Annual Volatility", "Volatility"], category: "risk",
    summary: "日收益标准差按 √252 年化后的波动程度。",
    definition: ["波动越大，净值路径通常越不稳定；它同时计入上涨和下跌波动。"],
    formula: "日收益样本标准差 × √252",
    systemConvention: ["页面按百分比展示。"],
    direction: "lower", directionLabel: "通常越低越稳",
    cautions: ["低波动不等于没有尾部风险。", ...commonCautions],
    related: ["max-drawdown", "cvar95", "sharpe-ratio", "ewma-volatility"],
    codeRefs: [ref("apps/api/app/services/quant.py", 216, "基金年化波动")],
  },
  {
    slug: "max-drawdown", title: "最大回撤", aliases: ["MDD", "Maximum Drawdown"], category: "risk",
    summary: "净值从历史高点到随后低点的最大跌幅。",
    definition: ["回答投资者在最差路径中可能经历多深的账面亏损。"],
    formula: "min(当前净值 ÷ 历史峰值 − 1)",
    systemConvention: ["本系统返回负数，例如 −20% 表示最大跌幅 20%。"],
    direction: "closer_to_zero", directionLabel: "越接近 0 越好",
    cautions: ["最大回撤依赖样本区间，未来可能出现更深回撤。", ...commonCautions],
    related: ["annual-volatility", "calmar-ratio", "cvar95"],
    codeRefs: [ref("apps/api/app/services/quant_stats.py", 109, "最大回撤")],
  },
  {
    slug: "cvar95", title: "CVaR95", aliases: ["Expected Shortfall", "ES95", "期望亏空"], category: "risk",
    summary: "历史样本中最差 5% 日收益的平均值。",
    definition: ["相比 VaR 只给阈值，CVaR 进一步衡量跌破阈值后平均有多差。"],
    formula: "排序后最差 ceil(5%×样本数) 个日收益的均值",
    systemConvention: ["本系统使用非参数历史模拟法，结果通常为负数。"],
    direction: "closer_to_zero", directionLabel: "越接近 0 越好",
    cautions: ["历史尾部样本少时估计很不稳定。", ...commonCautions],
    related: ["annual-volatility", "max-drawdown"],
    codeRefs: [ref("apps/api/app/services/quant_stats.py", 130, "CVaR95")],
  },
  {
    slug: "sharpe-ratio", title: "夏普比率", aliases: ["Sharpe Ratio", "夏普"], category: "risk",
    summary: "单位总波动带来的年化超额收益。",
    definition: ["衡量承担一单位收益波动获得多少超过无风险利率的收益。"],
    formula: "(日收益均值 − 2%÷252) ÷ 日收益标准差 × √252",
    systemConvention: ["本系统无风险利率固定为年化 2%，按 252 日折算。"],
    direction: "higher", directionLabel: "越高通常越好",
    interpretation: [{ range: "< 0", meaning: "样本期风险调整后表现弱于无风险利率" }, { range: "0～1", meaning: "正但有限的风险调整收益" }, { range: "> 1", meaning: "历史样本中较好，但仍需检验稳定性" }],
    cautions: ["短样本、非正态收益和过度调参会抬高夏普。", ...commonCautions],
    related: ["sortino-ratio", "calmar-ratio", "deflated-sharpe"],
    codeRefs: [ref("apps/api/app/services/quant_stats.py", 86, "夏普比率")],
  },
  {
    slug: "sortino-ratio", title: "索提诺比率", aliases: ["Sortino Ratio", "索提诺"], category: "risk",
    summary: "只用下行偏差惩罚风险的风险调整收益。",
    definition: ["上涨波动不被视为坏风险，因此更关注亏损方向。"],
    formula: "年化超额收益 ÷ 年化下行偏差",
    systemConvention: ["最低可接受收益使用 2% 年无风险利率的日化值。"],
    direction: "higher", directionLabel: "越高通常越好",
    cautions: ["下行样本很少时可能异常偏高。", ...commonCautions],
    related: ["sharpe-ratio", "downside-deviation"],
    codeRefs: [ref("apps/api/app/services/quant_discovery.py", 313, "Sortino实现")],
  },
  {
    slug: "downside-deviation", title: "下行偏差", aliases: ["Downside Deviation"], category: "risk",
    summary: "收益低于最低可接受收益部分的波动。",
    definition: ["只计算低于目标收益的负偏差，非负偏差按 0 计。"],
    systemConvention: ["本系统采用全样本 n 口径。"],
    direction: "lower", directionLabel: "越低越好",
    cautions: commonCautions,
    related: ["sortino-ratio"],
    codeRefs: [ref("apps/api/app/services/quant_discovery.py", 302, "下行偏差")],
  },
  {
    slug: "calmar-ratio", title: "Calmar 比率", aliases: ["Calmar Ratio", "卡玛比率"], category: "risk",
    summary: "年化收益相对于最大回撤的比率。",
    formula: "年化收益 ÷ |最大回撤|",
    definition: ["特别强调投资路径中最深回撤所换来的收益。"],
    systemConvention: ["回撤为 0 时该比率无稳定意义。"],
    direction: "higher", directionLabel: "越高通常越好",
    cautions: ["仅依赖一次最差回撤，容易受区间起止影响。", ...commonCautions],
    related: ["annualized-return", "max-drawdown", "sharpe-ratio"],
    codeRefs: [ref("apps/api/app/services/quant_stats.py", 143, "Calmar比率")],
  },
  {
    slug: "information-ratio", title: "信息比率", aliases: ["IR", "Information Ratio"], category: "validation",
    summary: "单位跟踪误差带来的主动收益。",
    formula: "策略−基准日收益均值 ÷ 主动收益标准差 × √252",
    definition: ["衡量策略相对基准的超额收益是否稳定。"],
    systemConvention: ["策略与基准按相同日期逐日配对。"],
    direction: "higher", directionLabel: "越高越好",
    cautions: ["必须确认策略和基准可投资范围、费用和日期完全一致。", ...commonCautions],
    related: ["excess-return", "tracking-error", "b0-benchmark"],
    codeRefs: [ref("apps/api/app/services/quant_stats.py", 162, "信息比率")],
  },
  {
    slug: "tracking-error", title: "跟踪误差", aliases: ["Tracking Error"], category: "risk",
    summary: "策略相对基准主动收益的标准差。",
    definition: ["越低表示越贴近基准，主动策略则不一定追求最低。"],
    systemConvention: ["信息比率的分母。"],
    direction: "contextual", directionLabel: "取决于策略目标",
    cautions: commonCautions,
    related: ["information-ratio", "b0-benchmark"],
    codeRefs: [ref("apps/api/app/services/quant_stats.py", 162, "跟踪误差口径")],
  },
  {
    slug: "momentum-12-1", title: "12-1 绝对动量", aliases: ["12-1 Momentum", "绝对动量"], category: "factors",
    summary: "过去约 12 个月、跳过最近 1 个月的收益。",
    formula: "t−21 日净值 ÷ t−252 日前一净值 − 1",
    definition: ["跳过最近 21 个交易日，是为了降低短期反转的影响。"],
    systemConvention: ["至少需要 253 个净值点；V2 入选要求动量 > 0。"],
    direction: "threshold", directionLabel: "越高越强；>0 才通过过滤",
    cautions: ["趋势切换时动量可能滞后。", ...commonCautions],
    related: ["relative-rank", "trend-strength", "risk-off"],
    codeRefs: [ref("apps/api/app/services/quant_risk.py", 177, "12-1动量")],
  },
  {
    slug: "momentum-score", title: "多窗口动量 MOM", aliases: ["MOM", "动量综合因子"], category: "factors",
    summary: "近 20、60、120 日收益的加权组合。",
    formula: "0.5×R20 + 0.3×R60 + 0.2×R120",
    definition: ["窗口不足时只使用可用项并重新归一化。"],
    systemConvention: ["用于规则模型 V1 的综合分。"],
    direction: "higher", directionLabel: "越高通常越强",
    cautions: commonCautions,
    related: ["risk-adjusted-momentum", "composite-score"],
    codeRefs: [ref("apps/api/app/services/quant_factors.py", 140, "多窗口动量")],
  },
  {
    slug: "risk-adjusted-momentum", title: "风险调整动量 RAM60", aliases: ["RAM60"], category: "factors",
    summary: "近 60 日日收益均值与波动的比值。",
    formula: "60 日日收益均值 ÷ 样本标准差",
    definition: ["比较同等波动下哪只基金的近期动量更强。"],
    systemConvention: ["标准差为 0 时返回空值。"],
    direction: "higher", directionLabel: "越高通常越好",
    cautions: commonCautions,
    related: ["momentum-score", "sharpe-ratio"],
    codeRefs: [ref("apps/api/app/services/quant_factors.py", 161, "RAM60")],
  },
  {
    slug: "trend-strength", title: "趋势强度", aliases: ["TREND", "MA20/MA60趋势"], category: "factors",
    summary: "基于现价、MA20 与 MA60 多空排列的趋势分数。",
    definition: ["现价高于均线、短均线高于长均线会提高趋势分。"],
    systemConvention: ["分值范围约 −1 到 +1。"],
    direction: "higher", directionLabel: "越高趋势越强",
    cautions: ["均线信号有滞后性。", ...commonCautions],
    related: ["momentum-12-1", "risk-off"],
    codeRefs: [ref("apps/api/app/services/quant_factors.py", 177, "趋势强度")],
  },
  {
    slug: "z-score", title: "横截面 z-score", aliases: ["标准分"], category: "factors",
    summary: "把指标转换成相对同组平均值的标准差单位。",
    formula: "(x − 横截面均值) ÷ 横截面标准差",
    definition: ["z=1 表示比同组平均高约一个标准差。"],
    systemConvention: ["样本少于 2 或标准差为 0 时有效值记 0。"],
    direction: "contextual", directionLabel: "方向取决于原始因子",
    cautions: commonCautions,
    related: ["winsorize", "composite-score"],
    codeRefs: [ref("apps/api/app/services/quant_factors.py", 212, "z-score")],
  },
  {
    slug: "winsorize", title: "Winsorize 缩尾", aliases: ["缩尾处理"], category: "factors",
    summary: "把极端值压到指定分位边界，降低异常点影响。",
    definition: ["不是删除样本，而是截断异常大或异常小的值。"],
    systemConvention: ["股票因子按行业做 1%/99% 缩尾；行业样本少于 8 时跳过。"],
    direction: "neutral", directionLabel: "数据处理方法，无好坏方向",
    cautions: commonCautions,
    related: ["z-score", "industry-neutral"],
    codeRefs: [ref("apps/api/app/services/stock_factors.py", 130, "行业缩尾")],
  },
  {
    slug: "quantile", title: "同类分位数", aliases: ["Percentile", "横截面分位"], category: "factors",
    summary: "指标在同类样本中的相对位置。",
    definition: ["90% 分位通常表示高于约 90% 的同类样本。"],
    systemConvention: ["本系统并列取平均秩；最高值为 (n−1)/n。", "小市场样本不足时会回退全权益池或中性处理。"],
    direction: "higher", directionLabel: "越高排名越靠前",
    cautions: ["不同市场或类型不能直接混比。", ...commonCautions],
    related: ["relative-rank", "tier-score"],
    codeRefs: [ref("apps/api/app/services/quant_factors.py", 229, "分位排名")],
  },
  {
    slug: "relative-rank", title: "层内排名", aliases: ["市场内排名", "Relative Rank"], category: "factors",
    summary: "基金在所属市场层内按动量排序的名次。",
    definition: ["#1 表示该市场层内最强。"],
    systemConvention: ["V2 每层取动量前 30%，向上取整至少 1 只。"],
    direction: "threshold", directionLabel: "名次数字越小越好",
    cautions: commonCautions,
    related: ["momentum-12-1", "quantile"],
    codeRefs: [ref("apps/api/app/services/quant_risk.py", 196, "层内选择")],
  },
  {
    slug: "composite-score", title: "基金综合分", aliases: ["SCORE", "规则综合分"], category: "factors",
    summary: "动量、风险调整动量、趋势和回撤的横截面加权分。",
    formula: "0.45×z(MOM)+0.35×z(RAM60)+0.20×TREND+0.50×z(DRAWDOWN)",
    definition: ["用于同一候选池内排序，不是预期收益率。"],
    systemConvention: ["缺失项按 0 处理。"],
    direction: "higher", directionLabel: "越高排序越靠前",
    cautions: ["分数没有货币或收益率单位。", ...commonCautions],
    related: ["momentum-score", "z-score", "tier-score"],
    codeRefs: [ref("apps/api/app/services/quant_factors.py", 250, "综合分")],
  },
  {
    slug: "tier-score", title: "五档评分", aliases: ["+2/+1/0/-1/-2", "五档模型"], category: "factors",
    summary: "把同市场分位和趋势转换为五个研究档位。",
    definition: ["+2 为值得进一步研究的强档，−2 为值得研究减配的弱档。"],
    systemConvention: ["前10%→+2，70%～90%→+1，30%～70%→0，10%～30%→−1，后10%→−2；±2 需要趋势配合。"],
    direction: "higher", directionLabel: "+2 高于 +1，高于 0",
    cautions: ["档位是规则研究结论，不是买卖指令。", ...commonCautions],
    related: ["quantile", "trend-strength", "risk-off"],
    codeRefs: [ref("apps/api/app/services/quant_factors.py", 281, "五档规则")],
  },
  {
    slug: "risk-off", title: "Risk-on / Risk-off", aliases: ["市场状态", "Regime"], category: "portfolio",
    summary: "根据指数趋势和动量判断市场风险状态。",
    definition: ["Risk-off 时规则模型会降低正向信号档位。"],
    systemConvention: ["Risk-off：指数低于 MA20 且 MA20<MA60，或近20日动量≤−5%；Risk-on 需要现价和均线多头排列且20日动量>0。"],
    direction: "neutral", directionLabel: "状态判断，无单调好坏",
    cautions: ["状态判定存在滞后和假突破。", ...commonCautions],
    related: ["trend-strength", "tier-score"],
    codeRefs: [ref("apps/api/app/services/quant_factors.py", 327, "市场状态")],
  },
  {
    slug: "hrp", title: "HRP 层次风险平价", aliases: ["Hierarchical Risk Parity", "分层风险平价"], category: "portfolio",
    summary: "利用相关性聚类和风险递归分配构建组合权重。",
    definition: ["先把行为相近的资产聚类，再按簇方差递归分配，避免直接求逆协方差矩阵。"],
    systemConvention: ["V2 市场层内优先 HRP；失败时回退逆波动率，再回退等权。"],
    direction: "neutral", directionLabel: "配置方法，无单一高低方向",
    cautions: ["相关性会随市场状态变化。", ...commonCautions],
    related: ["inverse-volatility", "equal-weight", "annual-volatility"],
    codeRefs: [ref("apps/api/app/services/quant_hrp.py", 171, "HRP权重")],
  },
  {
    slug: "inverse-volatility", title: "逆波动率配置", aliases: ["Inverse Volatility"], category: "portfolio",
    summary: "按波动率倒数分配权重，低波资产获得更高权重。",
    systemConvention: ["作为 HRP 的第一回退方案。"],
    direction: "neutral", directionLabel: "配置方法",
    cautions: ["可能集中到历史低波但未来风险上升的资产。", ...commonCautions],
    related: ["hrp", "annual-volatility", "equal-weight"],
    codeRefs: [ref("apps/api/app/services/quant_hrp.py", 233, "逆波动率")],
  },
  {
    slug: "equal-weight", title: "等权配置", aliases: ["Equal Weight"], category: "portfolio",
    summary: "所有入选资产使用相同权重。",
    systemConvention: ["既是配置回退，也用作 B0 简单基准。"],
    direction: "neutral", directionLabel: "配置方法",
    cautions: ["没有考虑波动、相关性、费用和容量。", ...commonCautions],
    related: ["b0-benchmark", "hrp"],
    codeRefs: [ref("apps/api/app/services/quant_hrp.py", 249, "等权回退")],
  },
  {
    slug: "b0-benchmark", title: "B0 等权基准", aliases: ["候选池等权基准", "Buy and Hold Benchmark"], category: "validation",
    summary: "全部有效候选等权买入持有的简单对照组合。",
    definition: ["用于判断复杂策略是否真的优于不择时的简单方案。"],
    systemConvention: ["V2 策略和基准在首个成交日同时锚定净值 1.0。"],
    direction: "neutral", directionLabel: "基准方法",
    cautions: ["基准也必须使用当时可投资的候选池。", ...commonCautions],
    related: ["excess-return", "information-ratio", "walk-forward"],
    codeRefs: [ref("apps/api/app/services/quant_v2.py", 478, "V2基准")],
  },
  {
    slug: "cash-weight", title: "现金权重", aliases: ["Cash Weight"], category: "portfolio",
    summary: "组合中没有配置到基金的资金比例。",
    definition: ["可能来自动量过滤、权重上限、波动率目标或主动空仓。"],
    systemConvention: ["现金默认零收益；值被限制在 0～100%。"],
    direction: "contextual", directionLabel: "不是越高或越低越好",
    cautions: ["高现金能降风险，也会在上涨期拖累收益。", ...commonCautions],
    related: ["vol-target-scalar", "weight-caps", "risk-off"],
    codeRefs: [ref("apps/api/app/services/quant_v2.py", 779, "现金权重")],
  },
  {
    slug: "vol-target-scalar", title: "波动率目标仓位系数", aliases: ["Volatility Targeting", "vol scalar"], category: "portfolio",
    summary: "实现波动超过目标时按比例降低整体基金仓位。",
    formula: "min(1, 目标波动 ÷ 实现波动)",
    systemConvention: ["目标波动 10%，带宽 10%，只降仓不加杠杆；系数 1 表示满仓。"],
    direction: "contextual", directionLabel: "接近 1 表示无需降仓",
    cautions: ["波动在危机中可能迅速上升，估计有滞后。", ...commonCautions],
    related: ["ewma-volatility", "cash-weight"],
    codeRefs: [ref("apps/api/app/services/quant_risk.py", 242, "波动目标")],
  },
  {
    slug: "ewma-volatility", title: "EWMA60 实现波动", aliases: ["RiskMetrics 波动率", "EWMA"], category: "risk",
    summary: "对近期收益赋予更高权重的年化波动估计。",
    formula: "σ²ₜ = 0.94×σ²ₜ₋₁ + 0.06×r²ₜ₋₁",
    systemConvention: ["最多使用尾部 60 个日收益，至少需要 20 个样本。"],
    direction: "lower", directionLabel: "越低通常越稳",
    cautions: commonCautions,
    related: ["annual-volatility", "vol-target-scalar", "freeze-rule"],
    codeRefs: [ref("apps/api/app/services/quant_risk.py", 221, "EWMA波动")],
  },
  {
    slug: "freeze-rule", title: "高波动急反弹冻结", aliases: ["冻结沿用", "Freeze Rule"], category: "portfolio",
    summary: "高波动下出现急反弹时，本期不调仓并沿用原持仓。",
    systemConvention: ["EWMA60 年化波动≥25%，且近5日复利收益≥8%或近10日≥12%时触发。"],
    direction: "neutral", directionLabel: "风控状态，无单调好坏",
    cautions: ["冻结可能避免追涨杀跌，也可能错过必要调仓。", ...commonCautions],
    related: ["ewma-volatility", "turnover"],
    codeRefs: [ref("apps/api/app/services/quant_risk.py", 272, "冻结规则")],
  },
  {
    slug: "weight-caps", title: "基金权重上限", aliases: ["单基金8%", "家族10%", "QDII30%"], category: "portfolio",
    summary: "限制单基金、同家族和海外资产的集中度。",
    systemConvention: ["V2 默认单基金≤8%、同家族≤10%、QDII/海外层合计≤30%，无法再分配部分留现金。"],
    direction: "neutral", directionLabel: "约束参数",
    cautions: ["上限过严会产生大量现金并拖累上涨期收益。", ...commonCautions],
    related: ["cash-weight", "fund-family", "turnover"],
    codeRefs: [ref("apps/api/app/services/quant_risk.py", 303, "权重约束")],
  },
  {
    slug: "fund-family", title: "基金家族与份额去重", aliases: ["A/C份额去重", "Share Class Dedup"], category: "fund-basics",
    summary: "识别同一底层基金的不同份额，避免重复配置。",
    systemConvention: ["去除公司前缀和 A/C/D 等份额后缀，同家族保留动量更高的一只。"],
    direction: "neutral", directionLabel: "数据处理方法",
    cautions: ["实际选择份额还应考虑申购费、销售服务费和预计持有期。"],
    related: ["weight-caps", "fund-share-class"],
    codeRefs: [ref("apps/api/app/services/quant_risk.py", 127, "家族识别")],
  },
  {
    slug: "turnover", title: "换手率", aliases: ["Turnover"], category: "portfolio",
    summary: "一次调仓中目标权重与漂移权重变化的单边总量。",
    formula: "Σ|目标权重 − 漂移权重| ÷ 2（含现金）",
    systemConvention: ["平均换手通常不计首次建仓。"],
    direction: "lower", directionLabel: "在收益相近时越低越好",
    cautions: ["低换手可能意味着反应慢，高换手会增加费用和滑点。", ...commonCautions],
    related: ["transaction-cost", "freeze-rule"],
    codeRefs: [ref("apps/api/app/services/quant_v2.py", 328, "换手率")],
  },
  {
    slug: "transaction-cost", title: "基金交易费用", aliases: ["申购费", "赎回费", "Transaction Cost"], category: "portfolio",
    summary: "调仓时产生的申购、赎回和短期持有费用。",
    systemConvention: ["统计验证默认买入0.15%、卖出0.5%、持有不足7天卖出1.5%；有真实流水时按FIFO lot估算。", "V2基础回测费用模型默认可为0，结果中会明确披露。"],
    direction: "lower", directionLabel: "越低越好",
    cautions: ["不同销售渠道、基金份额和持有期费率不同。"],
    related: ["turnover", "fifo-lot"],
    codeRefs: [ref("apps/api/app/services/quant_costs.py", 26, "费用默认值")],
  },
  {
    slug: "fifo-lot", title: "FIFO 持有批次", aliases: ["lot", "先进先出"], category: "portfolio",
    summary: "卖出时优先使用最早买入的份额批次估算持有期。",
    systemConvention: ["历史回测早于真实买入日时不使用负持有天数，而回退默认费率。"],
    direction: "neutral", directionLabel: "成本计算方法",
    cautions: commonCautions,
    related: ["transaction-cost"],
    codeRefs: [ref("apps/api/app/services/quant_costs.py", 127, "FIFO lot重建")],
  },
  {
    slug: "walk-forward", title: "Walk-Forward 滚动验证", aliases: ["滚动样本外验证"], category: "validation",
    summary: "反复用过去训练、随后未来一段测试的时间序列验证。",
    definition: ["每个测试窗口在打分时都不可见，用于模拟真实上线过程。"],
    systemConvention: ["step 必须不小于测试窗口，避免样本外收益重复累计；可设置 embargo 隔离带。"],
    direction: "neutral", directionLabel: "验证方法",
    cautions: ["它降低但不能消除过拟合和市场制度变化。"],
    related: ["oos", "embargo", "rank-ic", "b0-benchmark"],
    codeRefs: [ref("apps/api/app/services/quant_walkforward.py", 286, "Walk-Forward引擎")],
  },
  {
    slug: "oos", title: "样本外 OOS", aliases: ["Out-of-Sample", "留出测试"], category: "validation",
    summary: "没有参与参数选择和训练的数据区间。",
    systemConvention: ["样本外收益用于正式风险、IC、DSR和WRC评估。"],
    direction: "neutral", directionLabel: "验证概念",
    cautions: ["反复查看并据此调参会让样本外区间失去独立性。"],
    related: ["walk-forward", "embargo", "deflated-sharpe"],
    codeRefs: [ref("apps/api/app/services/quant_validation.py", 319, "样本外验证编排")],
  },
  {
    slug: "embargo", title: "Embargo 隔离带", aliases: ["Purged Walk-Forward", "时间隔离"], category: "validation",
    summary: "在训练与测试之间留出空窗，降低标签重叠造成的信息泄漏。",
    systemConvention: ["Walk-Forward 引擎支持 embargo；优化器通常使用测试窗口长度作为隔离。"],
    direction: "neutral", directionLabel: "验证方法",
    cautions: commonCautions,
    related: ["walk-forward", "oos"],
    codeRefs: [ref("apps/api/app/services/quant_walkforward.py", 293, "embargo参数")],
  },
  {
    slug: "rank-ic", title: "Rank IC", aliases: ["Spearman IC", "秩相关"], category: "validation",
    summary: "因子排序与未来收益排序的 Spearman 相关系数。",
    formula: "corr(rank(因子分), rank(前瞻收益))",
    systemConvention: ["并列取平均秩；每个调仓期计算后取均值。"],
    direction: "higher", directionLabel: "正且稳定越好",
    interpretation: [{ range: "≈ 0", meaning: "几乎没有稳定排序能力" }, { range: "> 0", meaning: "分数较高者未来收益倾向更高" }, { range: "< 0", meaning: "排序方向可能相反" }],
    cautions: ["Rank IC 0.03 不等于 3% 收益。", ...commonCautions],
    related: ["quintile-spread", "kendall-tau", "oos"],
    codeRefs: [ref("apps/api/app/services/quant_stats.py", 202, "Rank IC")],
  },
  {
    slug: "quintile-spread", title: "五档收益差 Q5−Q1", aliases: ["Quintile Spread"], category: "validation",
    summary: "最高分组和最低分组的平均前瞻收益差。",
    systemConvention: ["按因子分从低到高近似等分5组；至少10个样本。"],
    direction: "higher", directionLabel: "越高越好",
    cautions: commonCautions,
    related: ["rank-ic", "kendall-tau"],
    codeRefs: [ref("apps/api/app/services/quant_stats.py", 256, "五档单调性")],
  },
  {
    slug: "kendall-tau", title: "Kendall tau", aliases: ["组序相关", "Kendall τ"], category: "validation",
    summary: "五档组序与各组平均收益的秩相关。",
    systemConvention: ["本系统使用 tau-a，不修正并列；接近1表示收益随档位上升。"],
    direction: "higher", directionLabel: "越接近 1 越好",
    cautions: commonCautions,
    related: ["quintile-spread", "rank-ic"],
    codeRefs: [ref("apps/api/app/services/quant_stats.py", 240, "Kendall tau")],
  },
  {
    slug: "deflated-sharpe", title: "Deflated Sharpe Ratio", aliases: ["DSR", "膨胀修正夏普"], category: "validation",
    summary: "修正多重试验、偏度、峰度和有限样本后，夏普超过运气上界的概率。",
    systemConvention: ["结果在0～1；本系统实现为 Bailey/López de Prado 思路的简化近似。"],
    direction: "higher", directionLabel: "越接近 1 越好",
    interpretation: [{ range: "≥ 0.95", meaning: "常用的较严格显著门槛" }, { range: "≈ 0", meaning: "无法支持超出运气的结论" }],
    cautions: ["必须如实填写历史试验数。", ...commonCautions],
    related: ["sharpe-ratio", "trial-count", "white-reality-check"],
    codeRefs: [ref("apps/api/app/services/quant_stats.py", 369, "DSR")],
  },
  {
    slug: "white-reality-check", title: "White Reality Check", aliases: ["WRC", "Reality Check p值"], category: "validation",
    summary: "用循环块自助法检验策略相对基准的超额能力是否显著。",
    systemConvention: ["主动收益去均值后做 block bootstrap；默认500次、块长约√T、seed=42；当前为近似实现。"],
    direction: "lower", directionLabel: "p 值越低越好",
    interpretation: [{ range: "≤ 0.05", meaning: "常用显著门槛" }, { range: "> 0.05", meaning: "不能拒绝无超额能力的零假设" }],
    cautions: ["p值高不证明策略一定无效，只表示证据不足。", ...commonCautions],
    related: ["deflated-sharpe", "block-bootstrap", "excess-return"],
    codeRefs: [ref("apps/api/app/services/quant_stats.py", 475, "WRC")],
  },
  {
    slug: "block-bootstrap", title: "循环块 Bootstrap", aliases: ["Block Bootstrap", "循环块自助法"], category: "validation",
    summary: "按连续时间块重抽样，以保留收益序列的时间相关性。",
    systemConvention: ["块长默认 round(√T)，从环形序列随机起点抽连续块。"],
    direction: "neutral", directionLabel: "统计方法",
    cautions: commonCautions,
    related: ["white-reality-check"],
    codeRefs: [ref("apps/api/app/services/quant_stats.py", 413, "循环块重抽样")],
  },
  {
    slug: "trial-count", title: "历史试验数", aliases: ["Trial Count", "参数组合数"], category: "validation",
    summary: "过去评估过多少组模型或参数。",
    systemConvention: ["用于DSR多重比较修正；填1表示没有多重比较。"],
    direction: "neutral", directionLabel: "审计参数，无好坏方向",
    cautions: ["少报试验数会高估策略显著性。"],
    related: ["deflated-sharpe"],
    codeRefs: [ref("apps/api/app/services/quant_stats.py", 355, "期望最大夏普")],
  },
  {
    slug: "neighborhood-stability", title: "参数邻域稳定性", aliases: ["邻域经验分位", "Neighborhood Stability"], category: "validation",
    summary: "比较中心参数和附近参数的样本外表现，识别单点最优。",
    systemConvention: ["扰动 top_n、调仓间隔和因子权重；经验分位越高表示中心点不依赖偶然精确参数。"],
    direction: "higher", directionLabel: "经验分位越高越稳健",
    cautions: ["邻域稳定仍不能替代独立留出测试。", ...commonCautions],
    related: ["walk-forward", "oos"],
    codeRefs: [ref("apps/api/app/services/quant_stats.py", 565, "邻域稳定性")],
  },
  {
    slug: "pit-as-of", title: "PIT / as_of", aliases: ["Point-in-Time", "时间点快照"], category: "data",
    summary: "只使用在历史当时已经可见的数据。",
    definition: ["避免用今天知道的财务、成分或修订数据回测过去。"],
    systemConvention: ["数据需满足 available_at≤as_of；基金国内lag1、QDII lag2。"],
    direction: "neutral", directionLabel: "数据治理原则",
    cautions: ["忽略PIT会产生严重未来数据偏差。"],
    related: ["available-at", "lag-days", "survivorship-bias"],
    codeRefs: [ref("apps/api/app/research/snapshots.py", 1, "PIT元数据")],
  },
  {
    slug: "available-at", title: "effective / available / ingested 时间", aliases: ["available_at", "effective_date", "ingested_at"], category: "data",
    summary: "区分数据代表哪天、何时对市场可见、何时进入本系统。",
    systemConvention: ["回测依据 available_at，不依据今天是否已入库。"],
    direction: "neutral", directionLabel: "数据血缘概念",
    cautions: commonCautions,
    related: ["pit-as-of"],
    codeRefs: [ref("apps/api/app/research/snapshots.py", 3, "快照字段")],
  },
  {
    slug: "lag-days", title: "净值披露滞后", aliases: ["lag1", "lag2", "QDII滞后"], category: "data",
    summary: "信号日可用净值通常落后于业务日期。",
    systemConvention: ["国内基金默认lag1，QDII默认lag2；as_of当日净值不能假设已知。"],
    direction: "neutral", directionLabel: "数据可用性概念",
    cautions: commonCautions,
    related: ["pit-as-of", "t-plus-settlement"],
    codeRefs: [ref("apps/api/app/services/quant_snapshot.py", 30, "基金lag")],
  },
  {
    slug: "t-plus-settlement", title: "T+1 / QDII T+2", aliases: ["成交滞后", "Settlement Lag"], category: "portfolio",
    summary: "信号产生后按后续可得净值成交，避免信号日未来函数。",
    systemConvention: ["国内基金T+1，目标包含QDII时统一T+2。"],
    direction: "neutral", directionLabel: "成交规则",
    cautions: commonCautions,
    related: ["lag-days", "transaction-cost"],
    codeRefs: [ref("apps/api/app/services/quant_v2.py", 433, "成交日处理")],
  },
  {
    slug: "survivorship-bias", title: "幸存者偏差", aliases: ["Survivorship Bias"], category: "data",
    summary: "只用今天仍存在的基金或股票回测，会漏掉过去失败和退市样本。",
    systemConvention: ["当前基金候选池仍存在该残余偏差，方法说明中会披露；策略继续保持research_only。"],
    direction: "neutral", directionLabel: "方法学风险",
    cautions: ["幸存者偏差通常会让历史表现看起来更好。"],
    related: ["pit-as-of", "walk-forward", "b0-benchmark"],
    codeRefs: [ref("apps/api/app/services/quant_v2.py", 66, "V2方法说明")],
  },
  {
    slug: "research-ready", title: "研究就绪与历史覆盖率", aliases: ["nav_ready", "Coverage"], category: "data",
    summary: "基金净值是否达到规则计算所需的最少样本。",
    systemConvention: ["12-1动量和V2至少需要253个净值点；覆盖率=研究就绪基金数÷池成员数。"],
    direction: "higher", directionLabel: "覆盖率越高越可靠",
    cautions: ["样本数量达标不代表数据质量和幸存者偏差已经解决。"],
    related: ["momentum-12-1", "pit-as-of"],
    codeRefs: [ref("apps/api/app/services/candidate_pool.py", 45, "研究就绪门槛")],
  },
  {
    slug: "fund-share-class", title: "基金 A/C 等份额", aliases: ["Share Class", "A类", "C类"], category: "fund-basics",
    summary: "同一底层基金按费用结构区分的份额类别。",
    definition: ["A类常收申购费，C类常收销售服务费；实际优劣取决于渠道和持有期。"],
    direction: "contextual", directionLabel: "取决于费率和持有期",
    systemConvention: ["规则层先做家族去重，避免重复配置。"],
    cautions: ["不能只按净值趋势选择份额。"],
    related: ["fund-family", "transaction-cost"],
    codeRefs: [ref("apps/api/app/services/fund_catalog.py", 46, "份额识别")],
  },
  {
    slug: "pe", title: "市盈率 PE", aliases: ["P/E", "Price Earnings Ratio"], category: "stock-basics",
    summary: "股价相对于每股盈利的估值倍数。",
    formula: "股价 ÷ 每股收益",
    systemConvention: ["股票价值因子使用 EP=1/PE；按as_of读取当时估值。"],
    direction: "contextual", directionLabel: "通常低代表便宜，但不是越低越好",
    cautions: ["亏损公司PE无意义；行业间不可直接比较。"],
    related: ["ep", "pb", "roe"],
    codeRefs: [ref("apps/api/app/services/stock_repository.py", 563, "估值PIT")],
  },
  {
    slug: "pb", title: "市净率 PB", aliases: ["P/B", "Price to Book"], category: "stock-basics",
    summary: "股价相对于每股净资产的估值倍数。",
    direction: "contextual", directionLabel: "通常低代表便宜，但需结合资产质量",
    systemConvention: ["价值因子使用 BP=1/PB。"],
    cautions: ["轻资产行业和资产减值会削弱PB解释力。"],
    related: ["bp", "pe", "roe"],
    codeRefs: [ref("apps/api/app/services/stock_repository.py", 563, "PB转BP")],
  },
  {
    slug: "ep", title: "盈利收益率 EP", aliases: ["E/P", "Earnings Yield"], category: "stock-basics",
    summary: "市盈率的倒数，表示单位价格对应的盈利。",
    formula: "EP = 1 ÷ PE",
    direction: "higher", directionLabel: "通常越高越便宜",
    systemConvention: ["股票价值族因子之一。"],
    cautions: ["盈利波动和一次性损益会扭曲EP。"],
    related: ["pe", "bp"],
    codeRefs: [ref("apps/api/app/services/stock_repository.py", 638, "EP计算")],
  },
  {
    slug: "bp", title: "账面市值比 BP", aliases: ["B/P", "Book to Price"], category: "stock-basics",
    summary: "市净率的倒数。",
    formula: "BP = 1 ÷ PB",
    direction: "higher", directionLabel: "通常越高越便宜",
    systemConvention: ["股票价值族因子之一。"],
    cautions: ["需结合资产质量和行业。"],
    related: ["pb", "ep"],
    codeRefs: [ref("apps/api/app/services/stock_repository.py", 638, "BP计算")],
  },
  {
    slug: "roe", title: "净资产收益率 ROE", aliases: ["Return on Equity"], category: "stock-basics",
    summary: "公司利用股东权益创造利润的能力。",
    formula: "净利润 ÷ 平均净资产",
    direction: "higher", directionLabel: "通常越高越好",
    systemConvention: ["股票质量族因子之一，严格按披露日PIT使用。"],
    cautions: ["高杠杆、回购和一次性利润可能抬高ROE。"],
    related: ["pe", "pb", "industry-neutral"],
    codeRefs: [ref("apps/api/app/services/stock_factors.py", 59, "质量因子方向")],
  },
  {
    slug: "industry-neutral", title: "行业中性", aliases: ["Industry Neutral"], category: "stock-basics",
    summary: "在行业内比较因子并约束行业权重，降低行业暴露干扰。",
    systemConvention: ["行业内1%/99%缩尾和z-score；行业覆盖不足时股票正式回测会拒绝运行。"],
    direction: "neutral", directionLabel: "组合构建方法",
    cautions: ["行业分类体系和历史生效日期必须可靠。"],
    related: ["winsorize", "z-score"],
    codeRefs: [ref("apps/api/app/services/stock_factors.py", 330, "行业横截面")],
  },
];

export const KNOWLEDGE_BY_SLUG = new Map(KNOWLEDGE_ENTRIES.map((entry) => [entry.slug, entry]));

export function getKnowledgeEntry(slug: string): KnowledgeEntry | undefined {
  return KNOWLEDGE_BY_SLUG.get(slug);
}
